# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1455a19f0225904229693db8e2ee460c6a3b4a83b3af1353885b3e0ff205c06e38993853aee1b67d4e921d68610f448ff644142c8c8080f9a66b793d7c43d4b

test:
  secret_key_base: e903256257a7c06db9ce6483d367f97a2d5a536c0f013111814899e5c5cc3b499a055e6e1295bc27a0032f023c8611c7d2fd4695599a81411419880df80dddd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
